### ISSUE TITLE
Propagacja danych z bazy

### ISSUE THREAD

**Issue by luke-tester** [ZespolNumerJeden/zn1Skaner#10]

**Comment by luke-tester** [comment]
![ind2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cb73e26b51a100116837e8/125516c66e82c728ace21e0d46e19a9e71c0cfeb9ffbb049a15ee4d67304722a2a06f4782386e02ebe1a79045f5f4da5175a5911faa89b37b4f46d2ede0356b49b381d66cc2f13acb2831abe00bb268f4c8cb2bd8f48d2a5.png)
przykladowy kod kreskowych
powinien zwracac:


{
  "Id": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "FirstName": "Elon",
  "LastName": "Musk",
  "CompanyName": "SpaceX",
  "EventDate": "12/31/2018",
  "EventTime": "8:33 PM",
  "EventName": "Konferencja marsjańska",
  "WasInPast": false,
  "IsPresent": false
}

**Comment by krawan13** [comment]
testowy kod działa poprawnie. dla innych kodów po ich zeskanowaniu następuje przejście do ekranu głównego aplikacji oraz wyświetla się komunikat "Błąd skanowania"

**Comment by krawan13** [comment]
done
