### ISSUE TITLE
Ikonka aplikacji

### ISSUE THREAD

**Issue by luke-tester** [ZespolNumerJeden/zn1Skaner#13]
minimum 512x512px
druga 1024x1024px

**Comment by RadoslawBorzyszkowski** [comment]
![ico](https://user-images.githubusercontent.com/32323998/31688743-9c77e158-b38d-11e7-94f7-960d504764b4.png)

**Comment by RadoslawBorzyszkowski** [comment]
![5](https://user-images.githubusercontent.com/32323998/31688760-a75c7886-b38d-11e7-9184-6a18b250ac14.png)

**Comment by luke-tester** [comment]
zabieram się za podpięcie, dzięki @RadoslawBorzyszkowski! (zaimplementowana zostanie pierwsza wersja)
