### ISSUE TITLE
Grafika splashscreen

### ISSUE THREAD

**Issue by luke-tester** [ZespolNumerJeden/zn1Skaner#14]
720p
1080p
16:9, pionowa

**Comment by RadoslawBorzyszkowski** [comment]
![ico_720_v](https://user-images.githubusercontent.com/32323998/31689091-a748bb42-b38e-11e7-966a-d432e73cddf7.png)
![ico_1080_v](https://user-images.githubusercontent.com/32323998/31689092-a765fc0c-b38e-11e7-8a19-3d1f9f922d16.png)

**Comment by luke-tester** [comment]
zabieram się za podpięcie, dzięki @RadoslawBorzyszkowski !
