### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by luke-tester** [ZespolNumerJeden/zn1Skaner#15]
720p
16:9 
pozioma

**Comment by RadoslawBorzyszkowski** [comment]
![ico_720_h](https://user-images.githubusercontent.com/32323998/31689194-ef5fd96a-b38e-11e7-9c95-4a156b370141.png)
![ico_720_h2](https://user-images.githubusercontent.com/32323998/31689195-ef8574b8-b38e-11e7-9516-a6dce9682d61.png)

**Comment by luke-tester** [comment]
zabieram się za podpięcie, dzięki @RadoslawBorzyszkowski ! (zaimplementowana zostanie druga wersja)
