### ISSUE TITLE
Nowe wersje logo i ikon

### ISSUE THREAD

**Issue by luke-tester** [ZespolNumerJeden/zn1Skaner#20]
splashscreen:
- LDPI: 200x320px
 - MDPI: 320x480px
 - HDPI: 480x800px
 - XHDPI: 720px1280px
icon:
LDPI- icon-36x36
MDPI- icon-48x48
HDPI- icon 72x72
XHDPI- icon-96x96

**Comment by RadoslawBorzyszkowski** [comment]
![splash_LDPI_200x320.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fb849622918b96a3cd8f6a9b0fa0c4311575236b48e13b628ae92dbc56395b4d5a47ff135f5c47afaadf7aaee469708a5f02bbd36b0a72972f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e7828f4b3f1b031e8bff5927ed.png)

**Comment by RadoslawBorzyszkowski** [comment]
![splash_MDPI_320x480.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fb849622918b96a2cd8f6a9b0ea2c431127f236b48e13b628ae92dbc56395b4d5a47ff135f5c47afaadf7aaee469708a5f02bbd36b0a72972f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e7828f4b3f18051d8afd5827ed.png)

**Comment by RadoslawBorzyszkowski** [comment]
![splash_HDPI_480x800.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fb849622918b96a7cd8f6a9b09a8c4311e77236b48e13b628ae92dbc56395b4d5a47ff135f5c47afaadf7aaee469708a5f02bbd36b0a72972f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e7828f4b3f1b0d118bfa5527ed.png)

**Comment by RadoslawBorzyszkowski** [comment]
![splash_XHDPI_720x1280.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fb849622918b96b7c19b738d62a7c6795e76217154e1673295f127b54778154d555ca9480b0d43fffada78f0e73422df5c0beed83b5d72933b40bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8f463e1a041e88fa5e3ca28b06.png)

**Comment by RadoslawBorzyszkowski** [comment]
Teraz ikony:

**Comment by RadoslawBorzyszkowski** [comment]
![ico_LDPI_36x36.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46e197951caea799a6d6ec15bc0ea6d665043761260ea62864c7b96aea1b7803585c4dff120e0e4caeac892ba5bf6a728c090dbcc3714d36976345f3e5db55ea43a82a994e82bcbd8f4cc9e83924e188894e3f1d1755.png)

**Comment by RadoslawBorzyszkowski** [comment]
![ico_MDPI_48x48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46e197951cafa799a6d6eb1bbc09a8d665043761260ea62864c7b96aea1b7803585c4dff120e0e4caeac892ba5bf6a728c090dbcc3714d36976345f3e5db55ea43a82a994e82bcbd8f4cc9e83924e18f8c4737171755.png)

**Comment by RadoslawBorzyszkowski** [comment]
![ico_HDPI_72x72.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46e197951caaa799a6d6e811bc0aa2d665043761260ea62864c7b96aea1b7803585c4dff120e0e4caeac892ba5bf6a728c090dbcc3714d36976345f3e5db55ea43a82a994e8cbcbd8f4cc9e83924e18e8f4837181755.png)

**Comment by RadoslawBorzyszkowski** [comment]
![ico_XHDPI_96x96.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46e197951cbaab8dbfc0801af245a9c26b0a65633b0ba92e7391a172fd1722020d584daf120b0915f4abdc2ba6b53526885a5eeb807f4366846c4ff8e7df46f554f832815d84b1b68b49c0e13d21e68d8a493b1a030ac4.png)

**Comment by RadoslawBorzyszkowski** [comment]
![splash_HDPI_480x800.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fb849622918b96a7cd8f6a9b09a8c4311e77236b48e13b628ae92dbc56395b4d5a47ff135f5c47afaadf7aaee469708a5f02bbd36b0a72972f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e68b8a463a16041d8afe5d27ed.png)
![splash_LDPI_200x320.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fb849622918b96a3cd8f6a9b0fa0c4311575236b48e13b628ae92dbc56395b4d5a47ff135f5c47afaadf7aaee469708a5f02bbd36b0a72972f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e68b8a463a16041d8dfd5b27ed.png)
![splash_MDPI_320x480.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fb849622918b96a2cd8f6a9b0ea2c431127f236b48e13b628ae92dbc56395b4d5a47ff135f5c47afaadf7aaee469708a5f02bbd36b0a72972f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e68b8a463a16041d8aff5f27ed.png)
![splash_XHDPI_720x1280.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fb849622918b96b7c19b738d62a7c6795e76217154e1673295f127b54778154d555ca9480b0d43fffada78f0e73422df5c0beed83b5d72933b40bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8e4f3b17011088fa5e35a68b06.png)
