### ISSUE TITLE
Copy w aplikacji

### ISSUE THREAD

**Issue by luke-tester** [ZespolNumerJeden/zn1Skaner#26]
Proszę o sprawdzenie i ew. dostosowanie tekstów w aplikacji:

    <string name="app_name">Agile IT 3</string>
    <string name="scan">Skanuj</string>
    <string name="cancel">Anuluj</string>
    <string name="accept">Obecny</string>
    <string name="user_data_label">Dane uczestnika:</string>
    <string name="user_data_label_scan">Skanuj kod, aby pobrać dane uczestnika</string>
    <string name="welcomeBack">Witamy ponownie!</string>
    <string name="allRights">Agile IT (c) 2017</string>

    
    <string name="codeError">Błąd skanowania</string>
    <string name="apiError">Nieoczekiwany błąd połączenia z bazą</string>
    <string name="codeEmpty">Nie znaleziono biletu</string>
    <string name="codeAccepted">Oznaczono obecność uczestnika</string>
    <string name="codeCanceled">Anulowano skan</string>
    <string name="codeAlreadyPresent">Uczestnik już oznaczył swoją obecność</string>

    
    <string name="back_item_name">Wstecz</string>
    <string name="scanner_item_name">Skaner</string>
    <string name="agenda_item_name">Agenda</string>

**Comment by ghost** [comment]
Copyright Agile IT? Nawet jeśli miałoby chodzić o KN, to ono nie posiada tego trademarku. Może luke-tester lub ZespolNumerJeden a najlepiej jedno i drugie.

**Comment by luke-tester** [comment]
To tekst stopki, wpiszcie co chcecie, web ma ten sam tekst i dobrze by bylo uwspolnic.

**Comment by ghost** [comment]
No to niechaj będą jednakowe. I stały się podobne.

**Comment by ghost** [comment]
apiError  i codeError możnaby zmienić na 'Oznaczono obecność uczestnika' no a w WebApp też taki jeden komunikat błędu 'Aplikacja działa poprawnie'. Myślę, że nie ma się co czepiać, dopóki urządzenie się nie zawiesi.
