### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by luke-tester** [ZespolNumerJeden/zn1Skaner#9]

**Comment by luke-tester** [comment]
pure code implemented, get and put data in separated tasks

**Comment by krawan13** [comment]
na wafllu zn1Web 7 Przygotowanie API https://waffle.io/ZespolNumerJeden/zn1Web/cards/59d887ac1a6e1f00324e871f.  jest  :

gotowe, działa na branchu developerskim.
route: /api/ticket/{ticketId}

Request wymaga nagłówka z 'apiKey' - na razie dowolna wartość.

do GET i PATCH w contencie należy podać ticketId, który musi być Guid - przykładowe. które zwrócą zmockowane dane:

b18a464d-f0d3-428f-8774-1aba6ad02745
97036ce9-3e81-4b89-abed-2d7673b06679
f0f37ab1-89a0-48df-a647-4ef9f22efa14
2214b920-5869-42b6-9c00-9753a55d57f3

**Comment by luke-tester** [comment]
no i ? :) Nie bardzo rozumiem komentarz :) Wiem, że jest gotowe i zostanie zaimplementowane, logika jest już wpięta w apkę, osobny tsk jest na propagację danych :)
